import esbuild from "esbuild";
import process from "process";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, visit the plugin's repo
*/
`;

// Node built-in module names, kept as a plain array rather than depending on
// the "builtin-modules" npm package for one static list.
const NODE_BUILTINS = [
	"assert", "buffer", "child_process", "cluster", "console", "constants",
	"crypto", "dgram", "dns", "domain", "events", "fs", "http", "https",
	"module", "net", "os", "path", "process", "punycode", "querystring",
	"readline", "repl", "stream", "string_decoder", "sys", "timers", "tls",
	"tty", "url", "util", "v8", "vm", "zlib", "async_hooks", "http2", "perf_hooks",
];

const prod = process.argv[2] === "production";

// jszip depends on two IE-era polyfill packages -- "lie" (a Promise
// polyfill, itself requiring "immediate") and "setimmediate" -- both of
// which create <script> elements and use new Function() as legacy
// scheduling tricks. Neither ever actually runs: jszip only reaches for
// "lie" inside an `if (typeof Promise === "undefined")` branch, and
// "setimmediate" only defines global.setImmediate if it's missing --
// Obsidian's Electron/Node environment always has both natively. A
// bundler can't prove that statically, so without this plugin the dead
// code still ships (and trips security review). Stubbing both out here
// removes it entirely while preserving identical real-world behavior.
const stubOutLegacyPolyfillsPlugin = {
	name: "stub-out-legacy-polyfills",
	setup(build) {
		build.onResolve({ filter: /^lie$/ }, () => ({
			path: path.resolve(__dirname, "stubs/lie-stub.js"),
		}));
		build.onResolve({ filter: /^setimmediate$/ }, () => ({
			path: path.resolve(__dirname, "stubs/setimmediate-stub.js"),
		}));
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	plugins: [stubOutLegacyPolyfillsPlugin],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...NODE_BUILTINS,
	],
	format: "cjs",
	// jszip's package.json has a "browser" field mapping its main entry to
	// a PRE-BUNDLED dist/jszip.min.js (with "lie"/"immediate" already
	// merged inside, invisible to plugins/tree-shaking). esbuild defaults
	// to platform: "browser" and follows that mapping; "node" makes it use
	// jszip's real unbundled lib/index.js instead, matching how Obsidian
	// actually runs plugins (an Electron/Node CommonJS environment, not a
	// bare browser) and letting stubOutLegacyPolyfillsPlugin see the
	// imports it needs to intercept.
	platform: "node",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
