import JSZip from "jszip";

export interface ChapterInput {
	/** Chapter title, used as the <h1> and in the table of contents. */
	title: string;
	/** XHTML body fragment, as produced by convertNoteToXhtmlBody(). */
	xhtmlBody: string;
}

export interface ManuscriptMetadata {
	title: string;
	author: string;
	/** ISO 639-1 language code, e.g. "en". */
	language: string;
	/** Stable identifier for this book -- a UUID is generated by the caller if none is supplied. */
	identifier: string;
}

const CONTAINER_XML = `<?xml version="1.0" encoding="UTF-8"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <rootfiles>
    <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
  </rootfiles>
</container>
`;

const DEFAULT_STYLES = `
@page { margin: 5%; }
body { font-family: serif; line-height: 1.5; }
h1 { text-align: center; margin-top: 2em; margin-bottom: 1.5em; page-break-before: always; }
p { margin: 0; text-indent: 1.5em; }
p:first-of-type, h1 + p { text-indent: 0; }
p.scene-break { text-align: center; text-indent: 0; margin: 1.5em 0; }
blockquote { margin: 1em 2em; font-style: italic; }
`;

function chapterFileName(index: number): string {
	return `chapter-${String(index + 1).padStart(3, "0")}.xhtml`;
}

function chapterXhtml(chapter: ChapterInput, language: string): string {
	return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" lang="${language}">
<head>
  <meta charset="utf-8"/>
  <title>${escapeXml(chapter.title)}</title>
  <link rel="stylesheet" type="text/css" href="styles.css"/>
</head>
<body>
  <section epub:type="chapter">
    <h1>${escapeXml(chapter.title)}</h1>
${chapter.xhtmlBody}
  </section>
</body>
</html>
`;
}

function escapeXml(text: string): string {
	return text
		.replace(/&/g, "&amp;")
		.replace(/</g, "&lt;")
		.replace(/>/g, "&gt;")
		.replace(/"/g, "&quot;");
}

function navXhtml(chapters: ChapterInput[], meta: ManuscriptMetadata): string {
	const items = chapters
		.map((ch, i) => `      <li><a href="${chapterFileName(i)}">${escapeXml(ch.title)}</a></li>`)
		.join("\n");
	return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" lang="${meta.language}">
<head>
  <meta charset="utf-8"/>
  <title>${escapeXml(meta.title)} - Contents</title>
</head>
<body>
  <nav epub:type="toc" id="toc">
    <h1>Contents</h1>
    <ol>
${items}
    </ol>
  </nav>
</body>
</html>
`;
}

function tocNcx(chapters: ChapterInput[], meta: ManuscriptMetadata): string {
	const navPoints = chapters
		.map(
			(ch, i) => `    <navPoint id="navpoint-${i + 1}" playOrder="${i + 1}">
      <navLabel><text>${escapeXml(ch.title)}</text></navLabel>
      <content src="${chapterFileName(i)}"/>
    </navPoint>`
		)
		.join("\n");
	return `<?xml version="1.0" encoding="UTF-8"?>
<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1">
  <head>
    <meta name="dtb:uid" content="${escapeXml(meta.identifier)}"/>
    <meta name="dtb:depth" content="1"/>
    <meta name="dtb:totalPageCount" content="0"/>
    <meta name="dtb:maxPageNumber" content="0"/>
  </head>
  <docTitle><text>${escapeXml(meta.title)}</text></docTitle>
  <navMap>
${navPoints}
  </navMap>
</ncx>
`;
}

function contentOpf(chapters: ChapterInput[], meta: ManuscriptMetadata): string {
	const manifestItems = chapters
		.map((_ch, i) => `    <item id="chapter-${i + 1}" href="${chapterFileName(i)}" media-type="application/xhtml+xml"/>`)
		.join("\n");
	const spineItems = chapters.map((_ch, i) => `    <itemref idref="chapter-${i + 1}"/>`).join("\n");
	const modified = new Date().toISOString().replace(/\.\d+Z$/, "Z");

	return `<?xml version="1.0" encoding="UTF-8"?>
<package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="book-id">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:identifier id="book-id">${escapeXml(meta.identifier)}</dc:identifier>
    <dc:title>${escapeXml(meta.title)}</dc:title>
    <dc:creator>${escapeXml(meta.author)}</dc:creator>
    <dc:language>${escapeXml(meta.language)}</dc:language>
    <meta property="dcterms:modified">${modified}</meta>
  </metadata>
  <manifest>
    <item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/>
    <item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>
    <item id="styles" href="styles.css" media-type="text/css"/>
${manifestItems}
  </manifest>
  <spine toc="ncx">
${spineItems}
  </spine>
</package>
`;
}

/**
 * Builds a complete, spec-valid EPUB 3 file (with an EPUB2 toc.ncx included
 * too, for older reader compatibility) from already-converted chapters.
 * Returns the zip contents as an ArrayBuffer (not a Blob -- jszip's Blob
 * support depends on a browser-shaped global that plain Node test runs
 * don't have, and Obsidian's vault.createBinary()/modifyBinary() APIs
 * want an ArrayBuffer directly anyway), ready to be written to the vault.
 */
export async function buildEpub(chapters: ChapterInput[], meta: ManuscriptMetadata): Promise<ArrayBuffer> {
	if (chapters.length === 0) {
		throw new Error("Cannot build an EPUB with zero chapters.");
	}

	const zip = new JSZip();

	// The mimetype file MUST be the first entry and MUST be stored
	// uncompressed -- this is how EPUB readers distinguish a real EPUB
	// from an arbitrary zip file.
	zip.file("mimetype", "application/epub+zip", { compression: "STORE" });

	zip.folder("META-INF")?.file("container.xml", CONTAINER_XML);

	const oebps = zip.folder("OEBPS");
	if (!oebps) throw new Error("Failed to create OEBPS folder in EPUB archive.");

	oebps.file("content.opf", contentOpf(chapters, meta));
	oebps.file("nav.xhtml", navXhtml(chapters, meta));
	oebps.file("toc.ncx", tocNcx(chapters, meta));
	oebps.file("styles.css", DEFAULT_STYLES);

	chapters.forEach((chapter, i) => {
		oebps.file(chapterFileName(i), chapterXhtml(chapter, meta.language));
	});

	return zip.generateAsync({
		type: "arraybuffer",
		mimeType: "application/epub+zip",
		compression: "DEFLATE",
	});
}
